/**
 * Bulletproof Browser File Download Helper & Native PDF Generator
 * Triggers direct browser downloads without being blocked by popup blockers.
 */

export function downloadFile(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Creates a valid basic PDF document from text or HTML elements natively in browser JS
 */
export function createBasicPdf(title, contentText, filename) {
  // Simple PDF 1.4 header and text object structure
  const pdfHead = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>
endobj
4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
`;

  // Escape PDF parentheses
  const safeTitle = (title || "Document").replace(/[\(\)]/g, "");
  const lines = (contentText || "").split("\n").slice(0, 45); // First 45 lines per page
  
  let streamText = `BT /F1 18 Tf 50 740 Td (${safeTitle}) Tj ET\n`;
  streamText += `BT /F1 10 Tf 50 710 Td (Generated by FreeTooly) Tj ET\n`;
  
  let y = 680;
  lines.forEach((line) => {
    const safeLine = line.replace(/[\(\)]/g, "").substring(0, 80);
    if (safeLine.trim()) {
      streamText += `BT /F1 10 Tf 50 ${y} Td (${safeLine}) Tj ET\n`;
      y -= 14;
    }
  });

  const streamLength = streamText.length;
  const pdfBody = `5 0 obj
<< /Length ${streamLength} >>
stream
${streamText}endstream
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000244 00000 n 
0000000315 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
${315 + streamLength + 50}
%%EOF`;

  const fullPdf = pdfHead + pdfBody;
  const blob = new Blob([fullPdf], { type: "application/pdf" });
  downloadFile(blob, filename || "document.pdf");
}
